(ns compute-golden-test
  "Phase 3.1 (ADR-2607010930, re-scoped to kami-webgpu) — CLJC compute-golden for the cartpole
  @compute kernel. Two pins, both asserted here:

  1. MATH HASH — `fixtures/cartpole-compute-golden.json` records a fixed input-state + the
     SHA-256 of the output buffer state. We re-run the same semi-implicit Euler step in CLJC
     (`kami.cartpole-math/canonical-step`) and assert the hash matches. This locks the *math*
     (not wgpu execution): any change to the formula or input ripples into a different hash and
     fails here. The hash uses `%.12g` per component (the same 1e-12 tolerance the geometry
     goldens use), so sub-ULP cross-architecture `Math/sin`/`cos` noise doesn't perturb it.

  2. WGSL STRING PARITY — `fixtures/cartpole-compute-step.wgsl` is the WGSL string
     `kami.physics-compute/cartpole-step-emit` produces (regenerated by `nbb scripts/run-task.cljs gen-compute-golden`).
     We assert it carries the `@compute` / `@workgroup_size(...)` entry point, the storage + uniform
     bindings, and the struct declarations — the string-level parity markers `wgsl-parity` uses for
     vertex/fragment shaders. The committed fixture is the single source;
     `nbb scripts/run-task.cljs gen-compute-golden && git diff --exit-code` proves the emitter
     hasn't drifted from it. That drift check had been unenforceable since the generator's
     classpath went stale (ADR-2608135000) and the fixture header had in fact drifted; note that
     THIS test would not have caught it, because it asserts string-level markers rather than byte
     equality — only the regenerate-and-diff does.

  Why the test reaches `kami.cartpole-math` (this repo) and NOT `kami.physics-compute` (the
  kami-engine SDK): the two repos ship *different* `kami.wgsl` namespaces — kami-webgpu's is the
  low-level expr/stmt/func/binding* API (`wgsl-test`), the SDK's is the high-level
  emit/emit-compute-stage API that `cartpole-step-emit` needs. Putting the SDK on this JVM's
  classpath would shadow kami-webgpu's `kami.wgsl` and break `wgsl-test`. So the math is mirrored
  in `kami.cartpole-math` (shared by the gen script and this test), and only the gen script's
  separate process (SDK first on its classpath) calls the live emitter. This keeps the parity
  guarantee without a namespace collision."
  (:require [clojure.test :refer [deftest is run-tests testing]]
            [clojure.string :as str]
            [cheshire.core :as json]
            [kami.cartpole-math :as cm]))

(def ^:private golden-file  "fixtures/cartpole-compute-golden.json")
(def ^:private wgsl-file    "fixtures/cartpole-compute-step.wgsl")

(defn- load-golden [] (json/parse-string (slurp golden-file) true))

(deftest math-hash-matches-the-committed-golden
  (let [{:keys [input-state action cfg expected-output-hash hash-algorithm]} (load-golden)
        ;; the fixture's input must agree with the code's canonical input — guard drift in either direction
        canonical (cm/canonical-input)
        ;; the JSON cfg uses snake_case (the WGSL Cfg struct field names); the CLJC math uses
        ;; kebab-case keywords. Translate so we can compare values field-by-field.
        cfg-kebab {"cart-mass"        (:cart_mass cfg)
                   "pole-mass"        (:pole_mass cfg)
                   "pole-half-length" (:pole_half_length cfg)
                   "gravity"          (:gravity cfg)
                   "force-mag"        (:force_mag cfg)
                   "dt"               (:dt cfg)}]
    (is (= "sha256" hash-algorithm) "hash algorithm is pinned in the fixture")
    (is (= (vec (:state canonical)) (vec input-state))
        "fixture input-state matches kami.cartpole-math/canonical-input")
    (is (= (:action canonical) action)
        "fixture action matches kami.cartpole-math/canonical-input")
    (doseq [k (keys (:cfg canonical))]
      (is (= ((:cfg canonical) k) (get cfg-kebab (name k)))
          (str "fixture cfg " k " matches the canonical value")))
    ;; re-run the step from the fixture's input + the canonical cfg and hash it
    (let [out  (cm/step (:cfg canonical) input-state action)
          hash (cm/output-hash out)]
      (is (= expected-output-hash hash)
          (str "CLJC cartpole-step hash must equal the committed golden\n"
               "  expected " expected-output-hash "\n"
               "  actual   " hash)))
    ;; the canonical step (code's own input) must agree too
    (is (= expected-output-hash (cm/output-hash (cm/canonical-step)))
        "canonical-step hash matches the golden (input-state/code in sync)")))

(deftest emitted-wgsl-has-the-compute-parity-markers
  (let [wgsl (slurp wgsl-file)]
    (is (str/includes? wgsl "@compute") "entry point is a @compute stage")
    (is (str/includes? wgsl "@workgroup_size(") "workgroup size is declared")
    (is (str/includes? wgsl "@builtin(global_invocation_id)") "global-invocation-id builtin binds the lane")
    (is (str/includes? wgsl "fn step_main") "entry fn is step_main")
    (is (str/includes? wgsl "@group(0) @binding(0) var<storage, read_write> states")
        "states storage buffer (read_write) — the integrator's output buffer")
    (is (str/includes? wgsl "@group(0) @binding(1) var<storage, read> actions")
        "actions storage buffer (read) — the per-env force input")
    (is (str/includes? wgsl "@group(0) @binding(2) var<uniform> cfg")
        "cfg uniform — the physics constants binding")
    (is (str/includes? wgsl "struct State") "State struct declared")
    (is (str/includes? wgsl "struct Cfg") "Cfg struct declared")
    (is (str/includes? wgsl "Sutton & Barto 1983") "the formula source comment is preserved")
    (is (str/includes? wgsl "Semi-implicit Euler") "the integrator order comment is preserved")))

(deftest emitted-wgsl-mirrors-the-math-formula
  ;; The :wgsl/body and kami.cartpole-math/step must both advance x_dot/theta_dot before
  ;; x/theta (semi-implicit). We can't diff the WGSL against the SDK emitter here (see ns
  ;; docstring), but we CAN confirm the WGSL carries the same update ordering the CLJC uses.
  (let [wgsl (slurp wgsl-file)]
    (let [xdot-idx  (str/index-of wgsl "s.x_dot     = s.x_dot     + cfg.dt * x_acc;")
          x-idx     (str/index-of wgsl "s.x         = s.x         + cfg.dt * s.x_dot;")
          tdot-idx  (str/index-of wgsl "s.theta_dot = s.theta_dot + cfg.dt * theta_acc;")
          t-idx     (str/index-of wgsl "s.theta     = s.theta     + cfg.dt * s.theta_dot;")]
      (is (and xdot-idx x-idx (< xdot-idx x-idx))
          "x_dot is advanced before x (semi-implicit): x uses the new x_dot")
      (is (and tdot-idx t-idx (< tdot-idx t-idx))
          "theta_dot is advanced before theta (semi-implicit): theta uses the new theta_dot"))))

(let [{:keys [fail error]} (run-tests 'compute-golden-test)]
  (when (pos? (+ fail error))
    (throw (ex-info "compute-golden tests failed" {:fail fail :error error}))))
