(ns kami.webgpu
  "kami-webgpu — a WebGPU renderer driven entirely from CLJ/EDN (hiccup for WebGPU).

   ClojureScript calls the browser WebGPU JS API via w3.webgpu (org-w3-webgpu, the raw
   1:1 spec binding — ADR-2607051400) — no Rust, no wasm, no string marshaling. TWO
   kinds of data drive it:
     • the render GRAPH (shaders, targets, samplers, pipelines, an ordered :passes
       array) — EDN describing HOW a frame is drawn; built once in `init!`. Override it
       with (init! canvas {:graph ...}); reorder/add passes by editing data.
     • the render-IR (globals + instances) — EDN describing WHAT is in the frame; fed to
       `draw!` each requestAnimationFrame.
   The heavy rasterization is the GPU's; CLJS only records light per-frame commands. This
   is the web execution of the same EDN a native Rust/wgpu executor interprets (ADR-0001).
   The render-IR shape + pure constructors live in kami.webgpu.ir (.cljc, cross-platform)."
  (:require [kami.webgpu.ir :as ir]
            [kami.shaders :as shaders]
            [w3.webgpu :as w3]))

;; --- column-major mat4 (WebGPU/wgpu convention) ------------------------------

(defn- m4 [] (js/Float32Array. 16))
(defn- m4-mul [a b]
  (let [o (m4)]
    (dotimes [c 4]
      (dotimes [r 4]
        (aset o (+ (* c 4) r)
              (+ (* (aget a r)        (aget b (+ (* c 4) 0)))
                 (* (aget a (+ r 4))  (aget b (+ (* c 4) 1)))
                 (* (aget a (+ r 8))  (aget b (+ (* c 4) 2)))
                 (* (aget a (+ r 12)) (aget b (+ (* c 4) 3)))))))
    o))
(defn- m4-mulN [& ms] (reduce m4-mul ms))

(defn- perspective [fovy aspect near far]
  (let [f (/ 1.0 (js/Math.tan (/ fovy 2.0))) nf (/ 1.0 (- near far)) o (m4)]
    (aset o 0 (/ f aspect)) (aset o 5 f)
    (aset o 10 (* far nf)) (aset o 11 -1.0) (aset o 14 (* far near nf)) o))

(defn- ortho [l r b t near far]                ;; RH, depth 0..1 (wgpu) — for the sun
  (let [o (m4)]
    (aset o 0 (/ 2.0 (- r l))) (aset o 5 (/ 2.0 (- t b))) (aset o 10 (/ 1.0 (- near far)))
    (aset o 12 (- (/ (+ r l) (- r l)))) (aset o 13 (- (/ (+ t b) (- t b))))
    (aset o 14 (/ near (- near far))) (aset o 15 1.0) o))

(defn- v-sub [a b] [(- (a 0) (b 0)) (- (a 1) (b 1)) (- (a 2) (b 2))])
(defn- v-cross [a b] [(- (* (a 1) (b 2)) (* (a 2) (b 1)))
                      (- (* (a 2) (b 0)) (* (a 0) (b 2)))
                      (- (* (a 0) (b 1)) (* (a 1) (b 0)))])
(defn- v-norm [a] (let [l (js/Math.hypot (a 0) (a 1) (a 2)) l (if (< l 1e-9) 1.0 l)]
                    [(/ (a 0) l) (/ (a 1) l) (/ (a 2) l)]))
(defn- v-dot [a b] (+ (* (a 0) (b 0)) (* (a 1) (b 1)) (* (a 2) (b 2))))

(defn- look-at [eye center up]
  (let [f (v-norm (v-sub center eye))
        s (v-norm (v-cross f up))
        u (v-cross s f)
        o (m4)]
    (aset o 0 (s 0)) (aset o 4 (s 1)) (aset o 8 (s 2))
    (aset o 1 (u 0)) (aset o 5 (u 1)) (aset o 9 (u 2))
    (aset o 2 (- (f 0))) (aset o 6 (- (f 1))) (aset o 10 (- (f 2)))
    (aset o 12 (- (v-dot s eye))) (aset o 13 (- (v-dot u eye))) (aset o 14 (v-dot f eye))
    (aset o 15 1.0) o))

(defn- model-mat [[x y z] yaw w h]
  ;; translate(pos + up*h/2) * rotateY(yaw) * scale(w,h,w)
  (let [c (js/Math.cos yaw) s (js/Math.sin yaw)
        t (doto (m4) (aset 0 1)(aset 5 1)(aset 10 1)(aset 15 1)
                     (aset 12 x)(aset 13 (+ y (* h 0.5)))(aset 14 z))
        r (doto (m4) (aset 0 c)(aset 2 (- s))(aset 5 1)(aset 8 s)(aset 10 c)(aset 15 1))
        sc (doto (m4) (aset 0 w)(aset 5 h)(aset 10 w)(aset 15 1))]
    (m4-mulN t r sc)))

;; --- mesh buffers from the shared geometry source ----------------------------
;; The geometry itself is generated by kami.webgpu.geometry (.cljc) — the ONE cross-platform
;; source the native renderer also matches — and only interleaved into GPU buffers here.

(defn- mesh->buffers
  "Interleave a geometry mesh {:positions :normals :indices} into the renderer's vertex format
   (pos.xyz + normal.xyz, stride 24) and a uint16 index buffer."
  [{:keys [positions normals indices]}]
  [(js/Float32Array. (clj->js (vec (mapcat into positions normals))))
   (js/Uint16Array. (clj->js (vec indices)))])

;; The :geo mesh kinds are DATA now (kami.webgpu.ir/default-geometry); the executor bakes each
;; spec with ir/mesh-from-spec at init!. Unit meshes sized to the [w h] footprint the model
;; matrix scales (±0.5 like the cube). Pass {:geometry {…}} to init! to add/override a kind.

;; --- shaders (WGSL is data: referenced by the render graph) -------------------
;; eye (camera world pos) is packed into the spare .w of sun_dir/sun_col/sky. Lighting:
;; hemisphere ambient + Lambert sun + Blinn-Phong specular + Fresnel rim + shadow-map PCF,
;; Reinhard tonemap + gamma. PBR material (metallic/roughness/emissive) is per-instance EDN.
;; the ENTIRE shader is generated from data (kami.shaders/lit-shader via kami.wgsl): struct G,
;; uniform + shadow-map bindings, the PCF shadow fn, the VO varyings, the vertex and the fragment.
;; A bb token-equivalence gate (test/shader_test.clj) pins the generated WGSL to the on-screen-
;; verified original — identical token stream; only redundant grouping parens differ (always valid).
(def SHADER (shaders/lit-shader))

;; depth-only shadow pass: render instances from the sun's POV into the shadow map.
;; the depth-only shadow pass — also generated from data (kami.shaders/shadow-shader).
(def SHADOW-WGSL (shaders/shadow-shader))

;; --- the render graph, as EDN data -------------------------------------------

(def default-graph
  "The frame, described as data. :passes is an ordered array — the shadow pass renders
   depth into the :shadow target, then the main pass draws to the screen sampling it.
   Reorder/add passes, swap shaders, or retarget by editing this map (or pass {:graph ...}
   to init!). Each pipeline's :binds wires its group-0 resources by name."
  {:shaders   {:lit SHADER :depth SHADOW-WGSL}
   :targets   {:shadow {:depth "depth32float" :size [2048 2048]}}
   :samplers  {:comparison {:compare "less-equal" :magFilter "linear" :minFilter "linear"}}
   :pipelines {:shadow {:shader :depth :cull "back"
                        :depth {:format "depth32float" :write true :compare "less"}
                        :binds [:uniform]}
               :main   {:shader :lit :cull "back" :color :screen
                        :depth {:format "depth24plus" :write true :compare "less-equal"}
                        :binds [:uniform {:texture :shadow} {:sampler :comparison}]}}
   :passes    [{:pipeline :shadow :depth :shadow      :clear-depth 1.0}
               {:pipeline :main   :color :screen :depth :screen-depth :clear :sky}]})

;; ADR-2607100100 M6: this used to be a hard cap — draw! silently `take`-ing
;; the first MAX-INST instances and dropping the rest, a correctness gap for
;; genuinely large (city-scale) scenes, not a perf one (that's M4). It's now
;; only the STARTING allocation size for the GPU instance buffer; draw! grows
;; it (doubling) via [[ensure-inst-buffer!]] when a scene needs more. Kept at
;; the same value so typical scenes (<16384 instances) still pay zero extra
;; buffer churn versus before this fix.
(def ^:private INITIAL-INST-CAPACITY 16384)
(def ^:private INST-STRIDE 96)   ;; bytes/instance: model(16)+color(4)+material(4) floats

(defn- mk-inst-buffer [device capacity]
  (w3/create-buffer! device #js {:size (* capacity INST-STRIDE)
                                 :usage (bit-or (w3/buffer-usage :vertex) (w3/buffer-usage :copy-dst))}))

(defn- ensure-inst-buffer!
  "Grow `inst-buffer` (an atom of {:buf :capacity}) to hold at least `needed`
  instances, doubling from its current capacity (amortized-growth, same idea
  as a dynamic array) rather than resizing to the exact count every time an
  edge case adds one more instance. Destroys the old GPU buffer before
  replacing it. Returns {:buf <current-or-new buffer> :grew? bool} — callers
  use `grew?` to force a re-upload even on an otherwise-cached instance list,
  since a freshly (re)created buffer's contents are undefined until written."
  [inst-buffer device needed]
  (let [{:keys [buf capacity]} @inst-buffer]
    (if (<= needed capacity)
      {:buf buf :grew? false}
      (let [capacity' (loop [c (max capacity 1)] (if (>= c needed) c (recur (* c 2))))
            buf' (mk-inst-buffer device capacity')]
        (w3/destroy-buffer! buf)
        (reset! inst-buffer {:buf buf' :capacity capacity'})
        {:buf buf' :grew? true}))))

(defn- vattr [fmt off loc] #js {:format fmt :offset off :shaderLocation loc})
(defn- vlayout []   ;; cube(pos+normal, stride 24) + instance(model+color+material, stride 96)
  #js [#js {:arrayStride 24 :attributes #js [(vattr "float32x3" 0 0) (vattr "float32x3" 12 1)]}
       #js {:arrayStride 96 :stepMode "instance"
            :attributes #js [(vattr "float32x4" 0 2) (vattr "float32x4" 16 3) (vattr "float32x4" 32 4)
                             (vattr "float32x4" 48 5) (vattr "float32x4" 64 6) (vattr "float32x4" 80 7)]}])

(defn- build-pipeline [device fmt shaders {:keys [shader cull depth color]}]
  (let [mod (w3/create-shader-module! device #js {:code (get shaders shader)})
        desc #js {:layout "auto"
                  :vertex #js {:module mod :entryPoint "vs" :buffers (vlayout)}
                  :primitive #js {:cullMode (or cull "back")}
                  :depthStencil #js {:format (:format depth) :depthWriteEnabled (boolean (:write depth)) :depthCompare (:compare depth)}}]
    (when color   ;; no :color → depth-only pipeline (shadow pass)
      (set! (.-fragment desc) #js {:module mod :entryPoint "fs"
                                   :targets #js [#js {:format (if (= color :screen) fmt color)}]}))
    (w3/create-render-pipeline! device desc)))

(defn- build-bind   ;; wire group-0 entries from the pipeline's :binds vector (EDN)
  [device pipe gbuf targets samplers binds]
  (w3/create-bind-group! device
    #js {:layout (w3/get-bind-group-layout pipe 0)
         :entries (into-array
                    (map-indexed
                      (fn [i b]
                        (cond
                          (= b :uniform) #js {:binding i :resource #js {:buffer gbuf}}
                          (:texture b)   #js {:binding i :resource (get-in targets [(:texture b) :view])}
                          (:sampler b)   #js {:binding i :resource (get samplers (:sampler b))}))
                      binds))}))

(defn init!
  "Set up WebGPU on the canvas once from the render graph. Returns a Promise of a context.
   opts (optional): {:graph <render-graph EDN> :geometry <{:geo-kw {:type … params}} EDN>} —
   default to default-graph / ir/default-geometry (a {:geometry …} override is merged over it)."
  ([canvas] (init! canvas nil))
  ([canvas opts]
   (if-not (w3/supported?)
     (js/Promise.reject "WebGPU not available (use a recent Chrome/Edge)")
     (-> (w3/request-adapter!)
         (.then (fn [adapter] (w3/request-device! adapter)))
         (.then
           (fn [device]
             (let [graph (or (:graph opts) default-graph)
                   w (max 1 (.-clientWidth canvas)) h (max 1 (.-clientHeight canvas))
                   _ (set! (.-width canvas) w)
                   _ (set! (.-height canvas) h)
                   ctx (w3/get-context canvas)
                   fmt (w3/preferred-canvas-format)
                   q (.-queue device)
                   ;; writeBuffer REQUIRES COPY_DST or it silently no-ops → zero buffers.
                   mkbuf (fn [data usage]
                           (let [b (w3/create-buffer! device #js {:size (.-byteLength data)
                                                                  :usage (bit-or usage (w3/buffer-usage :copy-dst))})]
                             (w3/write-buffer! q b data) b))
                   ;; one vertex+index buffer per geometry kind, baked from EDN specs
                   ;; (ir/default-geometry + any {:geometry …} override); :geo picks a kind.
                   geom-specs (merge ir/default-geometry (:geometry opts))
                   geos (reduce-kv (fn [acc k spec]
                                     (let [[v i] (mesh->buffers (ir/mesh-from-spec spec))]
                                       (assoc acc k {:vbuf (mkbuf v (w3/buffer-usage :vertex))
                                                     :ibuf (mkbuf i (w3/buffer-usage :index))
                                                     :idx-count (.-length i)})))
                                   {} geom-specs)
                   box (:box geos)
                   inst-buffer (atom {:buf (mk-inst-buffer device INITIAL-INST-CAPACITY) :capacity INITIAL-INST-CAPACITY})
                   gbuf (w3/create-buffer! device #js {:size 240 :usage (bit-or (w3/buffer-usage :uniform) (w3/buffer-usage :copy-dst))})
                   ;; samplers from EDN
                   samplers (reduce-kv (fn [m k s] (assoc m k (w3/create-sampler! device (clj->js s)))) {} (:samplers graph))
                   ;; offscreen targets from EDN (RENDER_ATTACHMENT + sampleable) + implicit screen-depth
                   targets (reduce-kv
                             (fn [m k {:keys [depth color size]}]
                               (let [[tw th] (or size [w h])
                                     f (or depth color)
                                     tex (w3/create-texture! device #js {:size #js [tw th] :format f
                                                                         :usage (bit-or (w3/texture-usage :render-attachment) (w3/texture-usage :texture-binding))})]
                                 (assoc m k {:tex tex :view (w3/create-view tex) :format f})))
                             {} (:targets graph))
                   sdepth (w3/create-texture! device #js {:size #js [w h] :format "depth24plus" :usage (w3/texture-usage :render-attachment)})
                   targets (assoc targets :screen-depth {:view (w3/create-view sdepth) :format "depth24plus"})
                   ;; pipelines + bind groups, from EDN
                   pipelines (reduce-kv
                               (fn [m k pd]
                                 (let [pipe (build-pipeline device fmt (:shaders graph) pd)]
                                   (assoc m k {:pipe pipe :bind (build-bind device pipe gbuf targets samplers (:binds pd))})))
                               {} (:pipelines graph))]
               (w3/configure-context! ctx #js {:device device :format fmt :alphaMode "opaque"})
               {:device device :queue q :ctx ctx :fmt fmt :w w :h h
                :vbuf (:vbuf box) :ibuf (:ibuf box) :inst-buffer inst-buffer :gbuf gbuf :idx-count (:idx-count box)
                :geos geos
                :targets targets :pipelines pipelines :graph graph
                ;; ADR-2607100100 M4 investigation: a static scene's :instances is the
                ;; SAME value (by reference) across draw! calls in normal use (compose
                ;; the render-IR once, call draw! every rAF) — caching the sort/group/
                ;; marshal-to-Float32Array/GPU-upload work keyed on that reference turns
                ;; a static scene's per-frame cost from O(instance count) back to O(1).
                ;; See [[compute-instance-data]]/[[draw!]].
                :instance-cache (atom nil)})))))))

(defn- arr3 [m k d] (or (get m k) d))

(defn- compute-instance-data
  "Pure: sort instances by geometry kind (so each kind's instances are
  contiguous → one instanced draw per kind via a firstInstance offset —
  depth is handled by the z-buffer, so draw order is free), group them,
  compute the XZ centroid (the default-camera fallback point), and
  marshal the packed per-instance Float32Array (model matrix + color +
  material — everything [[draw!]] needs that depends ONLY on
  `raw-instances`, nothing on camera/lighting/sky). Factored out so
  `draw!` can cache it across frames when the instance list hasn't
  changed — see the `:instance-cache` note on [[init!]]. No count limit here
  — [[ensure-inst-buffer!]] grows the GPU buffer to fit however many
  `raw-instances` actually has (ADR-2607100100 M6; this used to silently
  `take MAX-INST` and drop the rest)."
  [raw-instances]
  (let [insts (->> raw-instances (sort-by #(name (or (:geo %) :box))) vec)
        geo-groups (loop [parts (partition-by #(or (:geo %) :box) insts), at 0, acc []]
                     (if (empty? parts)
                       acc
                       (let [p (first parts) c (count p)]
                         (recur (rest parts) (+ at c) (conj acc [(or (:geo (first p)) :box) c at])))))
        cz (reduce (fn [a {:keys [pos]}] [(+ (a 0) (pos 0)) (+ (a 1) (pos 2))]) [0 0] insts)
        n (max 1 (count insts))
        [cxx czz] [(/ (cz 0) n) (/ (cz 1) n)]
        idata (js/Float32Array. (* (count insts) 24))]   ;; model(16)+color(4)+material(4)
    (dotimes [i (count insts)]
      (let [{:keys [pos color size yaw metallic roughness emissive]} (nth insts i)
            m (model-mat pos (or yaw 0) ((or size [1 1]) 0) ((or size [1 1]) 1))
            base (* i 24)]
        (.set idata m base)
        (.set idata (clj->js [(color 0) (color 1) (color 2) 1]) (+ base 16))
        (.set idata (clj->js [(or metallic 0.0) (or roughness 0.65) (or emissive 0.0) 0]) (+ base 20))))
    {:raw-instances raw-instances :insts insts :geo-groups geo-groups :cxx cxx :czz czz :idata idata}))

(defn draw!
  "Draw one frame from a render-IR map: {:globals {:sky {:horizon :sun-dir :sun} :eye
   :target} :instances [{:pos :color :size :yaw :metallic :roughness :emissive}]}. Runs
   the graph's :passes in order. Synchronous; no wasm.

   Caches the sort/group/marshal-to-buffer work in `instance-cache` (see
   [[init!]]) keyed on `(:instances ir)` BY REFERENCE (`identical?`, not
   `=` — cheap, and correct for the common case of composing a render-IR
   once and calling `draw!` every rAF with that same value; a caller that
   rebuilds an equal-but-not-identical instances vector every frame just
   won't hit the cache, not a correctness issue). Only re-uploads the GPU
   instance buffer when the cache actually misses — ADR-2607100100's M4
   investigation measured a static scene's per-frame cost scaling with
   instance count purely from this redundant re-sort/re-marshal/re-upload
   (~36ms/frame at 20k instances), not from any GPU-side rendering limit.

   The GPU instance buffer itself grows (doubling) to fit however many
   instances the scene actually has — see [[ensure-inst-buffer!]] — rather
   than silently dropping any past a fixed cap (ADR-2607100100 M6)."
  [{:keys [device queue ctx w h vbuf ibuf inst-buffer gbuf idx-count targets pipelines graph geos instance-cache]} ir]
  (let [cached (some-> instance-cache deref)
        cache-hit? (and cached (identical? (:instances ir) (:raw-instances cached)))
        {:keys [insts geo-groups cxx czz idata]}
        (if cache-hit?
          cached
          (let [fresh (compute-instance-data (:instances ir))]
            (some-> instance-cache (reset! fresh))
            fresh))
        g (:globals ir)
        sky (:sky g)
        horizon (arr3 sky :horizon [0.7 0.8 0.9])
        sun-dir (arr3 sky :sun-dir [-0.4 -0.85 -0.35])
        sun (arr3 sky :sun [1 0.96 0.85])
        eye (arr3 g :eye [(+ cxx 60) 80 (+ czz 60)])
        target (arr3 g :target [cxx 0 czz])
        ;; projection as data: FOV (deg) + near/far planes from globals (defaults = the old look)
        fov (or (:fov g) 60) pnear (or (:near g) 0.5) pfar (or (:far g) 4000)
        vp (m4-mul (perspective (/ (* fov js/Math.PI) 180.0) (/ w (max 1 h)) pnear pfar)
                   (look-at (vec eye) (vec target) [0 1 0]))
        sl (let [l (js/Math.hypot (sun-dir 0) (sun-dir 1) (sun-dir 2)) l (if (< l 1e-6) 1.0 l)]
             [(/ (sun-dir 0) l) (/ (sun-dir 1) l) (/ (sun-dir 2) l)])
        ;; sun shadow frustum as data: ortho extent + near/far + light distance (defaults = old)
        shd (ir/shadow (:shadow g))
        sdist (:distance shd) sext (:extent shd)
        ltgt [cxx 0 czz]
        leye [(- (ltgt 0) (* (sl 0) sdist)) (- (ltgt 1) (* (sl 1) sdist)) (- (ltgt 2) (* (sl 2) sdist))]
        light-vp (m4-mul (ortho (- sext) sext (- sext) sext (:near shd) (:far shd)) (look-at leye ltgt [0 1 0]))
        ;; lighting-model coefficients as data: merge the frame's :lighting over the defaults
        ;; (omitting it reproduces the original baked-in constants exactly — parity, no change).
        lt (ir/lighting (:lighting g))
        amb (arr3 lt :ambient [0.20 0.22 0.26])
        gf (js/Float32Array. 60)]   ;; vp(16) sun_dir(4) sun_col(4) sky(4) light_vp(16) light_a/b/c/d(16)
    (.set gf vp 0)
    (.set gf (clj->js [(sun-dir 0) (sun-dir 1) (sun-dir 2) (nth eye 0)]) 16)
    (.set gf (clj->js [(sun 0) (sun 1) (sun 2) (nth eye 1)]) 20)
    (.set gf (clj->js [(horizon 0) (horizon 1) (horizon 2) (nth eye 2)]) 24)
    (.set gf light-vp 28)
    ;; light_a = [ambient.rgb, ambient-sky] · light_b = [spec-min spec-max rim rim-power]
    ;; light_c = [shininess-min shininess-max sun-diffuse metallic-diffuse-cut]
    (.set gf (clj->js [(amb 0) (amb 1) (amb 2) (:ambient-sky lt)]) 44)
    (.set gf (clj->js [(:spec-min lt) (:spec-max lt) (:rim lt) (:rim-power lt)]) 48)
    (.set gf (clj->js [(:shininess-min lt) (:shininess-max lt) (:sun-diffuse lt) (:metallic-diffuse-cut lt)]) 52)
    ;; light_d = [gamma, shadow-bias-slope, shadow-bias-min, shadow-texel]
    (.set gf (clj->js [(:gamma lt) (:shadow-bias-slope lt) (:shadow-bias-min lt) (:shadow-texel lt)]) 56)
    (w3/write-buffer! queue gbuf 0 gf)
    ;; grow the GPU instance buffer first if this frame's instance count
    ;; exceeds its current capacity (ADR-2607100100 M6) — then only
    ;; re-upload on a real cache miss OR a just-grown (contents-undefined)
    ;; buffer. See the :instance-cache note on init! and the draw! docstring.
    (let [{:keys [buf grew?]} (ensure-inst-buffer! inst-buffer device (count insts))]
      (when (or (not cache-hit?) grew?) (w3/write-buffer! queue buf 0 idata))
    (let [enc (w3/create-command-encoder! device)
          ninst (count insts)
          screen-view (w3/create-view (w3/current-texture ctx))
          vw (fn [k] (if (= k :screen) screen-view (get-in targets [k :view])))
          draw-geom (fn [p pipe bnd]
                      (when (pos? ninst)
                        (w3/set-pipeline! p pipe) (w3/set-bind-group! p 0 bnd)
                        (w3/set-vertex-buffer! p 1 buf)
                        ;; one instanced draw per geometry kind, offset into the instance buffer
                        (doseq [[gk gcount gfirst] geo-groups]
                          (let [{gv :vbuf gi :ibuf gn :idx-count} (get geos gk (:box geos))]
                            (w3/set-vertex-buffer! p 0 gv)
                            (w3/set-index-buffer! p gi "uint16")
                            (w3/draw-indexed! p gn gcount 0 0 gfirst)))))]
      ;; run the graph's passes in order (EDN-driven)
      (doseq [{:keys [pipeline color depth clear clear-depth]} (:passes graph)]
        (let [{:keys [pipe bind]} (get pipelines pipeline)
              catts (if color
                      (let [c (if (= clear :sky) horizon (or clear [0 0 0]))]
                        #js [#js {:view (vw color) :loadOp "clear" :storeOp "store"
                                  :clearValue #js {:r (c 0) :g (c 1) :b (c 2) :a 1}}])
                      #js [])
              rp (w3/begin-render-pass! enc
                   #js {:colorAttachments catts
                        :depthStencilAttachment #js {:view (vw depth) :depthLoadOp "clear"
                                                     :depthStoreOp "store" :depthClearValue (or clear-depth 1.0)}})]
          (draw-geom rp pipe bind)
          (w3/end-pass! rp)))
      (w3/submit! queue [(w3/finish! enc)])))))

(defn inst-buffer-capacity
  "How many instances the GPU instance buffer currently has room for
  (ADR-2607100100 M6) — an observability hook, not just for tests: lets a
  caller confirm a scene's instance count never silently exceeds what's
  actually being uploaded/drawn (`draw!` grows this as needed, so in normal
  use `capacity >= (count (:instances ir))` always holds after a call)."
  [ctx]
  (:capacity @(:inst-buffer ctx)))
