;; gen_pipeline_specs.clj — EDN → Rust codegen for the native render-pipeline specs.
;;
;; kami.pipelines/native-pipelines is the single source for the open-world pipelines' varying
;; fields (shader / cull / depth / blend). Rather than hand-maintain those in scene_pipelines.rs,
;; this emits a `pipeline_specs.rs` module (a const PipelineSpec table) FROM the EDN, so the native
;; side reads its spec from one source — the Tier B payoff over the parity gate (pipelines_test).
;; Same pattern as gen_wgsl / wit_test: --write emits the file; no flag reports parity; --strict throws.
;;
;;   bb gen-pipeline-specs            # parity report (committed fixture vs freshly generated)
;;   bb gen-pipeline-specs --write    # write fixtures/pipeline_specs.rs (+ native copy if co-located)
;;   bb gen-pipeline-specs --strict   # throw on drift
(require '[kami.pipelines :as pl]
         '[clojure.string :as str]
         '[clojure.java.io :as io])

(def native-rs "../kami-engine/kami-render/src/pipeline_specs.rs")  ;; native copy (when co-located)
(def fixture   "fixtures/pipeline_specs.rs")

(defn- cull-variant [c] (case c :back "Cull::Back" :front "Cull::Front" "Cull::None"))
(defn- blend-variant [b] (case b :alpha "Blend::Alpha" "Blend::None"))

(defn- spec-line [[id {:keys [shader cull depth-write depth-compare blend]}]]
  (format "    PipelineSpec { name: %s, shader: %s, cull: %s, depth_write: %s, depth_compare: %s, blend: %s },"
          (pr-str (name id)) (pr-str shader) (cull-variant cull)
          (boolean depth-write) (pr-str (name depth-compare)) (blend-variant blend)))

(defn gen-rust []
  (let [sorted (sort-by (comp name key) pl/native-pipelines)]
    (str
     "// GENERATED by `bb gen-pipeline-specs` from kami.pipelines/native-pipelines — do not edit.\n"
     "// The native open-world render pipelines as data, single-sourced from the EDN descriptor.\n"
     "// Regenerate with `bb gen-pipeline-specs --write`; `bb gen-pipeline-specs --strict` gates drift.\n\n"
     "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n"
     "pub enum Cull { None, Back, Front }\n\n"
     "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n"
     "pub enum Blend { None, Alpha }\n\n"
     "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n"
     "pub struct PipelineSpec {\n"
     "    pub name: &'static str,\n"
     "    pub shader: &'static str,\n"
     "    pub cull: Cull,\n"
     "    pub depth_write: bool,\n"
     "    pub depth_compare: &'static str,\n"
     "    pub blend: Blend,\n"
     "}\n\n"
     (format "pub const PIPELINE_SPECS: [PipelineSpec; %d] = [\n" (count sorted))
     (str/join "\n" (map spec-line sorted)) "\n"
     "];\n")))

(defn- canon [s] (-> s (str/replace #"//[^\n]*" "") (str/replace #"\s" "")))

(let [rust (gen-rust)
      args (set *command-line-args*)]
  (cond
    (args "--write")
    (do (io/make-parents (io/file fixture))
        (spit fixture rust)
        (when (.exists (io/file (.getParent (io/file native-rs)))) (spit native-rs rust))
        (println (format "wrote pipeline_specs.rs (%d pipelines) → fixtures%s"
                         (count pl/native-pipelines)
                         (if (.exists (io/file (.getParent (io/file native-rs)))) " + native" ""))))
    :else
    (let [f (io/file fixture)]
      (println "── pipeline_specs.rs — kami.pipelines EDN → Rust ──")
      (if-not (.exists f)
        (println "  (no committed fixture yet — run --write)")
        (let [match? (= (canon (slurp f)) (canon rust))]
          (println (if match? "  ✓ committed fixtures/pipeline_specs.rs is in sync with the EDN"
                              "  ✗ DRIFT — fixtures/pipeline_specs.rs ≠ generated (run --write)"))
          (when (and (args "--strict") (not match?))
            (throw (ex-info "pipeline_specs.rs drift (Rust ≠ kami.pipelines EDN)" {}))))))))
