#!/usr/bin/env nbb
;; Auto-generated by bb_edn_to_nbb_tasks.cljs (ADR-2607173000).
;;   nbb scripts/run-task.cljs <task> [args…]
(require '[clojure.edn :as edn]
         '[clojure.string :as str])

(def fs (js/require "node:fs"))
(def path (js/require "node:path"))
(def cp (js/require "node:child_process"))

(defn- sh [argv]
  (let [r (.spawnSync cp (first argv) (to-array (rest argv))
                      #js {:encoding "utf8" :stdio "inherit" :shell false})]
    (or (.-status r) 1)))

(def tasks-path (.join path (.dirname path *file*) "tasks.edn"))
(def tasks (edn/read-string (.readFileSync fs tasks-path "utf8")))

(defn- resolve-task [task]
  (or (get tasks (keyword task))
      (get tasks task)
      (get tasks (symbol task))))

(defn- run-one [task rest-args]
  (let [t (resolve-task task)]
    (when-not t
      (binding [*out* *err*] (println "unknown task:" task)
        (println "known:" (str/join ", " (map name (sort (keys tasks))))))
      (.exit js/process 2))
    (cond
      (:runs t)
      (doseq [r (:runs t)]
        (let [code (run-one r rest-args)]
          (when-not (zero? code) (.exit js/process code))))
      (:cmd t)
      (let [argv (if (:pass-args? t)
                   (into (vec (:cmd t)) rest-args)
                   (vec (:cmd t)))]
        (sh argv))
      :else
      (do (binding [*out* *err*] (println "bad task entry" task t))
          (.exit js/process 2)))))

(let [args (vec *command-line-args*)
      args (if (and (seq args) (str/includes? (str (first args)) "run-task"))
             (subvec args 1) args)
      task (first args)
      rest-args (vec (rest args))]
  (when-not task
    (binding [*out* *err*]
      (println "usage: nbb scripts/run-task.cljs <task> [args…]")
      (println "tasks:" (str/join ", " (map name (sort (keys tasks))))))
    (.exit js/process 2))
  (.exit js/process (or (run-one task rest-args) 0)))
