#!/usr/bin/env nbb
;; Auto-generated by bb_edn_to_nbb_tasks.cljs (ADR-2607173000).
;;   nbb scripts/run-task.cljs <task> [args…]
(require '[clojure.edn :as edn]
         '[clojure.string :as str])

(def fs (js/require "node:fs"))
(def path (js/require "node:path"))
(def cp (js/require "node:child_process"))

(defn- sh [argv]
  (let [r (.spawnSync cp (first argv) (to-array (rest argv))
                      #js {:encoding "utf8" :stdio "inherit" :shell false})]
    ;; A child that never started, and one killed by a signal, BOTH report
    ;; status:null and land on the synthetic exit 1 -- with nothing printed,
    ;; because stdio is inherited and there was no child to write anything.
    ;; Say which it was: an exit 1 with no output is indistinguishable from a
    ;; command that ran and failed quietly.
    (when-let [e (.-error r)]
      (js/console.error "run-task: could not start" (pr-str argv) "--" (.-message e)))
    (when-let [sig (.-signal r)]
      (js/console.error "run-task:" (pr-str (first argv)) "killed by signal" sig))
    (or (.-status r) 1)))

(def tasks-path (.join path (.dirname path *file*) "tasks.edn"))
(def tasks (edn/read-string (.readFileSync fs tasks-path "utf8")))

(defn- resolve-task [task]
  (or (get tasks (keyword task))
      (get tasks task)
      (get tasks (symbol task))))

(defn- run-one [task rest-args]
  (let [t (resolve-task task)]
    (when-not t
      ;; js/console.error, NOT (binding [*out* *err*] (println …)) -- nbb does
      ;; not honour that binding and the text lands on stdout (ADR-2608130600).
      (js/console.error "unknown task:" task)
      (js/console.error "known:" (str/join ", " (map name (sort (keys tasks)))))
      (.exit js/process 2))
    (cond
      (:runs t)
      (doseq [r (:runs t)]
        (let [code (run-one r rest-args)]
          (when-not (zero? code) (.exit js/process code))))
      (:cmd t)
      (let [argv (if (:pass-args? t)
                   (into (vec (:cmd t)) rest-args)
                   (vec (:cmd t)))]
        (sh argv))
      :else
      (do (js/console.error "bad task entry" task t)
          (.exit js/process 2)))))

(let [args (vec *command-line-args*)
      args (if (and (seq args) (str/includes? (str (first args)) "run-task"))
             (subvec args 1) args)
      task (first args)
      rest-args (vec (rest args))]
  (when-not task
    (js/console.error "usage: nbb scripts/run-task.cljs <task> [args…]")
    (js/console.error "tasks:" (str/join ", " (map name (sort (keys tasks)))))
    (.exit js/process 2))
  (.exit js/process (or (run-one task rest-args) 0)))
